CREATE TABLE profile (
    id integer,
    created bigint,
    last_edit bigint,
    last_active bigint,
    status integer,
    anonymous boolean,
    rank integer,
    name text,
    age integer,
    tags text[],
    description text,
    city text,
    latitude real,
    longitude real,
    city_latitude real,
    city_longitude real,
    photo_id text,
    likes integer,
    reports integer,
    gender integer,
    relationships boolean,
    search_gender integer,
    search_mode integer
);